apps/shop/urls.py
from django.urls import path, include
from apps.shop import views

app_name = 'shop'
urlpatterns = [
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='product'),
    path('ordering/', views.ordering, name='ordering'),
    path('pay-confirm/', views.create_order_view, name='pay_confirm'),
    path('', views.shop, name='shop')
]




config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('apps.shop.urls')),
    path('', include('apps.landing.urls'))
]


if DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/header.html
{% load static %}

<div class="wp-site-blocks">
    <header class="alignfull wp-block-template-part">
        <div class="wp-block-group alignfull has-ti-bg-alt-background-color has-background has-global-padding is-layout-constrained wp-block-group-is-layout-constrained" style="padding-top:20px;padding-right:0px;padding-bottom:20px;padding-left:0px">
            <div class="wp-block-group alignwide is-layout-flow wp-block-group-is-layout-flow" style="padding-right:20px;padding-left:20px">
                <div class="wp-block-group is-content-justification-space-between is-nowrap is-layout-flex wp-container-core-group-is-layout-1 wp-block-group-is-layout-flex">
                    <h1 style="text-transform:uppercase;" class="wp-block-site-title has-large-font-size">
                        <a href="/" target="_self" rel="home" aria-current="page">
                            ottosender
                        </a>
                    </h1>

                    <nav class="is-responsive items-justified-right wp-block-navigation is-content-justification-right is-layout-flex wp-container-core-navigation-is-layout-1 wp-block-navigation-is-layout-flex" aria-label="Навигация Заголовок" data-wp-interactive="core/navigation" data-wp-context='{"overlayOpenedBy":{"click":false,"hover":false,"focus":false},"type":"overlay","roleAttribute":"","ariaLabel":"\u041c\u0435\u043d\u044e"}'>
                        <button aria-haspopup="dialog" aria-label="Открыть меню" class="wp-block-navigation__responsive-container-open " data-wp-on--click="actions.openMenuOnClick" data-wp-on--keydown="actions.handleMenuKeydown">
                            <svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" aria-hidden="true" focusable="false">
                                <rect x="4" y="7.5" width="16" height="1.5"></rect>
                                <rect x="4" y="15" width="16" height="1.5"></rect>
                            </svg>
                        </button>
				        <div class="wp-block-navigation__responsive-container  " style="" id="modal-1" data-wp-class--has-modal-open="state.isMenuOpen" data-wp-class--is-menu-open="state.isMenuOpen" data-wp-watch="callbacks.initMenu" data-wp-on--keydown="actions.handleMenuKeydown" data-wp-on--focusout="actions.handleMenuFocusout" tabindex="-1">
                            <div class="wp-block-navigation__responsive-close" tabindex="-1">
                                <div class="wp-block-navigation__responsive-dialog" data-wp-bind--aria-modal="state.ariaModal" data-wp-bind--aria-label="state.ariaLabel" data-wp-bind--role="state.roleAttribute">
                                    <button aria-label="Закрыть меню" class="wp-block-navigation__responsive-container-close" data-wp-on--click="actions.closeMenuOnClick">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false">
                                            <path d="M13 11.8l6.1-6.3-1-1-6.1 6.2-6.1-6.2-1 1 6.1 6.3-6.5 6.7 1 1 6.5-6.6 6.5 6.6 1-1z"></path>
                                        </svg>
                                    </button>
                                    <div class="wp-block-navigation__responsive-container-content" data-wp-watch="callbacks.focusFirstElement" id="modal-1-content">
                                        <ul class="wp-block-navigation__container is-responsive items-justified-right wp-block-navigation">
                                            <li class=" wp-block-navigation-item wp-block-navigation-link">
                                                <a class="wp-block-navigation-item__content" href="/">
                                                    <span class="wp-block-navigation-item__label">
                                                        Главная
                                                    </span>
                                                </a>
                                            </li>
                                            <li class=" wp-block-navigation-item wp-block-navigation-link">
                                                <a class="wp-block-navigation-item__content" href="{% url 'shop:shop' %}">
                                                    <span class="wp-block-navigation-item__label">
                                                        Корзина
                                                    </span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
				        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>